# Nanonets API Configuration
[nanonets]
NANONETS_API_KEY = "c6e05194-e5eb-11ef-aea2-62ed866fc8a9"  # Replace with your actual Nanonets API key
NANONETS_MODEL_ID = "24ed5d9e-fe88-4da8-a22c-1ec06ab783d2"   # Replace with your actual Nanonets model ID 